### ISSUE TITLE
Playback doesn't work

### ISSUE THREAD

**Issue by ottoleipala** [flathub/org.kde.juk#33]
There is problem with phonon it doesn't play any audio files...

`WARNING: bool Phonon::FactoryPrivate::createBackend() phonon backend plugin could not be loaded
WARNING: bool Phonon::FactoryPrivate::createBackend() phonon backend plugin could not be loaded
WARNING: bool Phonon::FactoryPrivate::createBackend() phonon backend plugin could not be loaded
WARNING: bool Phonon::FactoryPrivate::createBackend() phonon backend plugin could not be loaded
WARNING: Phonon::createPath: Cannot connect  Phonon::MediaObject ( no objectName ) to  Phonon::AudioOutput ( no objectName ).
WARNING: bool Phonon::FactoryPrivate::createBackend() phonon backend plugin could not be loaded
WARNING: bool Phonon::FactoryPrivate::createBackend() phonon backend plugin could not be loaded
Couldn't start kwalletd:  QDBusError("org.freedesktop.DBus.Error.ServiceUnknown", "The name org.kde.kwalletd6 was not provided by any .service files")
Couldn't start kwalletd:  QDBusError("org.freedesktop.DBus.Error.ServiceUnknown", "The name org.kde.kwalletd6 was not provided by any .service files")
Couldn't start kwalletd:  QDBusError("org.freedesktop.DBus.Error.ServiceUnknown", "The name org.kde.kwalletd6 was not provided by any .service files")
Couldn't start kwalletd:  QDBusError("org.freedesktop.DBus.Error.ServiceUnknown", "The name org.kde.kwalletd6 was not provided by any .service files")
Couldn't start kwalletd:  QDBusError("org.freedesktop.DBus.Error.ServiceUnknown", "The name org.kde.kwalletd6 was not provided by any .service files")
Couldn't start kwalletd:  QDBusError("org.freedesktop.DBus.Error.ServiceUnknown", "The name org.kde.kwalletd6 was not provided by any .service files")
Couldn't start kwalletd:  QDBusError("org.freedesktop.DBus.Error.ServiceUnknown", "The name org.kde.kwalletd6 was not provided by any .service files")
Couldn't start kwalletd:  QDBusError("org.freedesktop.DBus.Error.ServiceUnknown", "The name org.kde.kwalletd6 was not provided by any .service files")
kf.i18n: 0 instead of 1 arguments to message "<i>Lyrics are curren..." supplied before conversion
WARNING: bool Phonon::FactoryPrivate::createBackend() phonon backend plugin could not be loaded
WARNING: bool Phonon::FactoryPrivate::createBackend() phonon backend plugin could not be loaded
`

**Comment by tsdgeos** [comment]
In a few hours https://github.com/flathub/org.kde.juk/pull/34 will have a build and instructions on how to test it.

If possible for you to test we would appreciate you could confirm if that fixes the issue.

**Comment by ottoleipala** [comment]
I installed and playback is fixed thanks..

**Comment by tsdgeos** [comment]
Thanks a lot for testing and for the report :)

**Comment by ottoleipala** [comment]
Yeah no problem, i'm acctualy in Mageia Linux qa quality assurance team testing packages goes to updates....
